server.port=8080
server.servlet.context-path=/api

spring.application.name=MONIFY - Sistema de Organizacao Financeira
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/monify_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=America/Sao_Paulo
logging.level.com.monify=INFO
